### ISSUE TITLE
Spacing a bit different than the Dobot mockup

### ISSUE THREAD

**Issue by acacheung** [catchsparrow/catchsparrow.github.io#6]
- too much spacing below logo
- too much spacing above "Check out how this was made" link

**Comment by catchsparrow** [comment]
I had adjusted the spacing above each separate 'check out how this was
made' link to be as it is in the photoshop doc, i.e much larger for the
first product than the third, but I have now changed the CSS so the spacing
is the same throughout it all and is now smaller, looks better that way!
Hope that is ok!

**Comment by acacheung** [comment]
:+1:

**Comment by catchsparrow** [comment]
Hey sorry to bother you again! I was experimenting with css style for my blog post today and was looking at my dobot style for guidance. When I went to check everything was still working for dobot there was something strange going on so I must have made an accidental change... I think i have now fixed it to back how it was but can you just confirm it's all still there?
